@startuml "Modelo Conceitual"

abstract class Usuario {

    Id: Long

    nome : String

    email: String

    datanasc: Date

    senha: String

 

}  

 

class Consultor {

    active: boolean

    area: String

    avaliacao: float 

    site: String

}

 

class Cliente {

    tipoCliente: String

}



 class Favoritos {

    consultoresFavs: String

}

 


class Consultoria{

    Id: Integer

    data: Date

    tempodeduracao: time

}

 

 class PagamentoConsultoria {
  
   id : Integer

   FormaDePagamento: String

   DataPagamento: Date
}

class PrecoConsultoria{

   PrecoConsultoria : float

}
 

class Agenda {

    Id: Long

    dayWeek: DayOfWeek

    startTime: LocalTime

    endTime: LocalTime

   

}

 

Class Categoria{

    Id: Integer

    nome: String

}

 

Class Conteudo{

  tipo: String

  Id: Integer

  nome: String 

  url: 

}

Class Feedback{

    Id: String

    tipo: String

    avaliacao: float

}

 

 
Cliente -- Favoritos

Favoritos -- Consultor

Consultor -- Categoria

Categoria o-- Conteudo

Consultor --|> Usuario

Usuario <|-- Cliente

Consultoria --Feedback

Cliente -- Consultoria

Consultoria -- Consultor

Consultor o-- Agenda

PagamentoConsultoria --* Consultoria

PrecoConsultoria -- Consultoria

Consultor -- PrecoConsultoria


@enduml

 