@startuml "Modelo Conceitual"

abstract class Usuario {

    Id: Long

    nome : String

    email: String

    telefone: String

    datanasc: Date

    genero: String

    endereco: String

    senha: String


}

 

class Consultor {

    idConsultor: Long

    contaBancaria: String 

    valorHora: Double

    status: Boolean

    avaliacao: float 

    contato: String

    site: String

}

 

class Cliente {

    idCliente: Long

}



 class AgendaConsultor {

    horaInicio: Time

    horaFim: Time

    diaSemana: DayOfWeek


}



class Consultoria{

    idConsultoria: Long

    data: Date

    horario: LocalTime

    tempodeDuracao: time

}

 

 class PagamentoConsultoria {
  
   idPagamento: Long

   FormaDePagamento: String

   extrato: String
}

 

 class Assinatura{

     idAssinatura: Long

     dataInicio: Date

     dataFim: Date

     valor: Double
 }

 

Class Categoria{

    idCategoria: Long

    descricao: String

}

 

Class Conteudo{

  tipo: String

  descricao: String

  idCategoria: Integer

}

Class Feedback{

    idFeedback: Long

    comentario: String

    estrela: Integer

}

 

Consultor --|> Usuario

Usuario <|-- Cliente 
 
Cliente -- Consultor : Favoritos

Consultor o-- AgendaConsultor

Consultor -- Categoria

Consultor -- Conteudo

Conteudo o-- Categoria

Consultor -- Consultoria

Consultoria -- Feedback

Consultoria *-- PagamentoConsultoria

Assinatura -- Cliente

Cliente -- Consultoria


@enduml

 